apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 3000
      targetPort: 3000
<<<<<<< HEAD
      nodePort: 30007
=======
      nodePort: 30007
>>>>>>> dd42308 (update)
